// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6srzYkZIVlccknMZaHOGcbjiXuZ9zikk',
    appId: '1:197949395607:web:49592509b6129f5d85cfd2',
    messagingSenderId: '197949395607',
    projectId: 'alanv1-51180',
    authDomain: 'alanv1-51180.firebaseapp.com',
    storageBucket: 'alanv1-51180.firebasestorage.app',
    measurementId: 'G-HD270B1HGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpsHGKYHVoZHl8XtSSdu8Rj3FqXTnZYDE',
    appId: '1:197949395607:android:333f4380387cd5fb85cfd2',
    messagingSenderId: '197949395607',
    projectId: 'alanv1-51180',
    storageBucket: 'alanv1-51180.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcwlR5Hq582AQNiVPeRRrVBruXX6RWXYg',
    appId: '1:197949395607:ios:e2992a558f9303fc85cfd2',
    messagingSenderId: '197949395607',
    projectId: 'alanv1-51180',
    storageBucket: 'alanv1-51180.firebasestorage.app',
    iosBundleId: 'com.example.emotionJournal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcwlR5Hq582AQNiVPeRRrVBruXX6RWXYg',
    appId: '1:197949395607:ios:e2992a558f9303fc85cfd2',
    messagingSenderId: '197949395607',
    projectId: 'alanv1-51180',
    storageBucket: 'alanv1-51180.firebasestorage.app',
    iosBundleId: 'com.example.emotionJournal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6srzYkZIVlccknMZaHOGcbjiXuZ9zikk',
    appId: '1:197949395607:web:18936b74e330020085cfd2',
    messagingSenderId: '197949395607',
    projectId: 'alanv1-51180',
    authDomain: 'alanv1-51180.firebaseapp.com',
    storageBucket: 'alanv1-51180.firebasestorage.app',
    measurementId: 'G-NSPCD9E0VL',
  );
}
